
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Condominium` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Condominium
 * 
 */
export type CondominiumModel = runtime.Types.Result.DefaultSelection<Prisma.$CondominiumPayload>

export type AggregateCondominium = {
  _count: CondominiumCountAggregateOutputType | null
  _min: CondominiumMinAggregateOutputType | null
  _max: CondominiumMaxAggregateOutputType | null
}

export type CondominiumMinAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CondominiumMaxAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CondominiumCountAggregateOutputType = {
  id: number
  name: number
  slug: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CondominiumMinAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  createdAt?: true
  updatedAt?: true
}

export type CondominiumMaxAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  createdAt?: true
  updatedAt?: true
}

export type CondominiumCountAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CondominiumAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Condominium to aggregate.
   */
  where?: Prisma.CondominiumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Condominiums to fetch.
   */
  orderBy?: Prisma.CondominiumOrderByWithRelationInput | Prisma.CondominiumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CondominiumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Condominiums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Condominiums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Condominiums
  **/
  _count?: true | CondominiumCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CondominiumMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CondominiumMaxAggregateInputType
}

export type GetCondominiumAggregateType<T extends CondominiumAggregateArgs> = {
      [P in keyof T & keyof AggregateCondominium]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCondominium[P]>
    : Prisma.GetScalarType<T[P], AggregateCondominium[P]>
}




export type CondominiumGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CondominiumWhereInput
  orderBy?: Prisma.CondominiumOrderByWithAggregationInput | Prisma.CondominiumOrderByWithAggregationInput[]
  by: Prisma.CondominiumScalarFieldEnum[] | Prisma.CondominiumScalarFieldEnum
  having?: Prisma.CondominiumScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CondominiumCountAggregateInputType | true
  _min?: CondominiumMinAggregateInputType
  _max?: CondominiumMaxAggregateInputType
}

export type CondominiumGroupByOutputType = {
  id: string
  name: string
  slug: string
  createdAt: Date
  updatedAt: Date
  _count: CondominiumCountAggregateOutputType | null
  _min: CondominiumMinAggregateOutputType | null
  _max: CondominiumMaxAggregateOutputType | null
}

export type GetCondominiumGroupByPayload<T extends CondominiumGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CondominiumGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CondominiumGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CondominiumGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CondominiumGroupByOutputType[P]>
      }
    >
  >



export type CondominiumWhereInput = {
  AND?: Prisma.CondominiumWhereInput | Prisma.CondominiumWhereInput[]
  OR?: Prisma.CondominiumWhereInput[]
  NOT?: Prisma.CondominiumWhereInput | Prisma.CondominiumWhereInput[]
  id?: Prisma.StringFilter<"Condominium"> | string
  name?: Prisma.StringFilter<"Condominium"> | string
  slug?: Prisma.StringFilter<"Condominium"> | string
  createdAt?: Prisma.DateTimeFilter<"Condominium"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Condominium"> | Date | string
  users?: Prisma.UserListRelationFilter
  residents?: Prisma.ResidentListRelationFilter
  visitors?: Prisma.VisitorListRelationFilter
  events?: Prisma.EventListRelationFilter
  incidents?: Prisma.IncidentListRelationFilter
  serviceProviders?: Prisma.ServiceProviderListRelationFilter
  authorizations?: Prisma.AuthorizationListRelationFilter
  accessRecords?: Prisma.AccessRecordListRelationFilter
}

export type CondominiumOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  users?: Prisma.UserOrderByRelationAggregateInput
  residents?: Prisma.ResidentOrderByRelationAggregateInput
  visitors?: Prisma.VisitorOrderByRelationAggregateInput
  events?: Prisma.EventOrderByRelationAggregateInput
  incidents?: Prisma.IncidentOrderByRelationAggregateInput
  serviceProviders?: Prisma.ServiceProviderOrderByRelationAggregateInput
  authorizations?: Prisma.AuthorizationOrderByRelationAggregateInput
  accessRecords?: Prisma.AccessRecordOrderByRelationAggregateInput
}

export type CondominiumWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.CondominiumWhereInput | Prisma.CondominiumWhereInput[]
  OR?: Prisma.CondominiumWhereInput[]
  NOT?: Prisma.CondominiumWhereInput | Prisma.CondominiumWhereInput[]
  name?: Prisma.StringFilter<"Condominium"> | string
  createdAt?: Prisma.DateTimeFilter<"Condominium"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Condominium"> | Date | string
  users?: Prisma.UserListRelationFilter
  residents?: Prisma.ResidentListRelationFilter
  visitors?: Prisma.VisitorListRelationFilter
  events?: Prisma.EventListRelationFilter
  incidents?: Prisma.IncidentListRelationFilter
  serviceProviders?: Prisma.ServiceProviderListRelationFilter
  authorizations?: Prisma.AuthorizationListRelationFilter
  accessRecords?: Prisma.AccessRecordListRelationFilter
}, "id" | "slug">

export type CondominiumOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CondominiumCountOrderByAggregateInput
  _max?: Prisma.CondominiumMaxOrderByAggregateInput
  _min?: Prisma.CondominiumMinOrderByAggregateInput
}

export type CondominiumScalarWhereWithAggregatesInput = {
  AND?: Prisma.CondominiumScalarWhereWithAggregatesInput | Prisma.CondominiumScalarWhereWithAggregatesInput[]
  OR?: Prisma.CondominiumScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CondominiumScalarWhereWithAggregatesInput | Prisma.CondominiumScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Condominium"> | string
  name?: Prisma.StringWithAggregatesFilter<"Condominium"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Condominium"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Condominium"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Condominium"> | Date | string
}

export type CondominiumCreateInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordCreateNestedManyWithoutCondominiumInput
}

export type CondominiumUncheckedCreateInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentUncheckedCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorUncheckedCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderUncheckedCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationUncheckedCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordUncheckedCreateNestedManyWithoutCondominiumInput
}

export type CondominiumUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUncheckedUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUncheckedUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUncheckedUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUncheckedUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUncheckedUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumCreateManyInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CondominiumUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CondominiumUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CondominiumScalarRelationFilter = {
  is?: Prisma.CondominiumWhereInput
  isNot?: Prisma.CondominiumWhereInput
}

export type CondominiumCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CondominiumMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CondominiumMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CondominiumCreateNestedOneWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutUsersInput, Prisma.CondominiumUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutUsersInput
  connect?: Prisma.CondominiumWhereUniqueInput
}

export type CondominiumUpdateOneRequiredWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutUsersInput, Prisma.CondominiumUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutUsersInput
  upsert?: Prisma.CondominiumUpsertWithoutUsersInput
  connect?: Prisma.CondominiumWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CondominiumUpdateToOneWithWhereWithoutUsersInput, Prisma.CondominiumUpdateWithoutUsersInput>, Prisma.CondominiumUncheckedUpdateWithoutUsersInput>
}

export type CondominiumCreateNestedOneWithoutResidentsInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutResidentsInput, Prisma.CondominiumUncheckedCreateWithoutResidentsInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutResidentsInput
  connect?: Prisma.CondominiumWhereUniqueInput
}

export type CondominiumUpdateOneRequiredWithoutResidentsNestedInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutResidentsInput, Prisma.CondominiumUncheckedCreateWithoutResidentsInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutResidentsInput
  upsert?: Prisma.CondominiumUpsertWithoutResidentsInput
  connect?: Prisma.CondominiumWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CondominiumUpdateToOneWithWhereWithoutResidentsInput, Prisma.CondominiumUpdateWithoutResidentsInput>, Prisma.CondominiumUncheckedUpdateWithoutResidentsInput>
}

export type CondominiumCreateNestedOneWithoutVisitorsInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutVisitorsInput, Prisma.CondominiumUncheckedCreateWithoutVisitorsInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutVisitorsInput
  connect?: Prisma.CondominiumWhereUniqueInput
}

export type CondominiumUpdateOneRequiredWithoutVisitorsNestedInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutVisitorsInput, Prisma.CondominiumUncheckedCreateWithoutVisitorsInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutVisitorsInput
  upsert?: Prisma.CondominiumUpsertWithoutVisitorsInput
  connect?: Prisma.CondominiumWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CondominiumUpdateToOneWithWhereWithoutVisitorsInput, Prisma.CondominiumUpdateWithoutVisitorsInput>, Prisma.CondominiumUncheckedUpdateWithoutVisitorsInput>
}

export type CondominiumCreateNestedOneWithoutServiceProvidersInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutServiceProvidersInput, Prisma.CondominiumUncheckedCreateWithoutServiceProvidersInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutServiceProvidersInput
  connect?: Prisma.CondominiumWhereUniqueInput
}

export type CondominiumUpdateOneRequiredWithoutServiceProvidersNestedInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutServiceProvidersInput, Prisma.CondominiumUncheckedCreateWithoutServiceProvidersInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutServiceProvidersInput
  upsert?: Prisma.CondominiumUpsertWithoutServiceProvidersInput
  connect?: Prisma.CondominiumWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CondominiumUpdateToOneWithWhereWithoutServiceProvidersInput, Prisma.CondominiumUpdateWithoutServiceProvidersInput>, Prisma.CondominiumUncheckedUpdateWithoutServiceProvidersInput>
}

export type CondominiumCreateNestedOneWithoutAuthorizationsInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutAuthorizationsInput, Prisma.CondominiumUncheckedCreateWithoutAuthorizationsInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutAuthorizationsInput
  connect?: Prisma.CondominiumWhereUniqueInput
}

export type CondominiumUpdateOneRequiredWithoutAuthorizationsNestedInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutAuthorizationsInput, Prisma.CondominiumUncheckedCreateWithoutAuthorizationsInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutAuthorizationsInput
  upsert?: Prisma.CondominiumUpsertWithoutAuthorizationsInput
  connect?: Prisma.CondominiumWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CondominiumUpdateToOneWithWhereWithoutAuthorizationsInput, Prisma.CondominiumUpdateWithoutAuthorizationsInput>, Prisma.CondominiumUncheckedUpdateWithoutAuthorizationsInput>
}

export type CondominiumCreateNestedOneWithoutAccessRecordsInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutAccessRecordsInput, Prisma.CondominiumUncheckedCreateWithoutAccessRecordsInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutAccessRecordsInput
  connect?: Prisma.CondominiumWhereUniqueInput
}

export type CondominiumUpdateOneRequiredWithoutAccessRecordsNestedInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutAccessRecordsInput, Prisma.CondominiumUncheckedCreateWithoutAccessRecordsInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutAccessRecordsInput
  upsert?: Prisma.CondominiumUpsertWithoutAccessRecordsInput
  connect?: Prisma.CondominiumWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CondominiumUpdateToOneWithWhereWithoutAccessRecordsInput, Prisma.CondominiumUpdateWithoutAccessRecordsInput>, Prisma.CondominiumUncheckedUpdateWithoutAccessRecordsInput>
}

export type CondominiumCreateNestedOneWithoutEventsInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutEventsInput, Prisma.CondominiumUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutEventsInput
  connect?: Prisma.CondominiumWhereUniqueInput
}

export type CondominiumUpdateOneRequiredWithoutEventsNestedInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutEventsInput, Prisma.CondominiumUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutEventsInput
  upsert?: Prisma.CondominiumUpsertWithoutEventsInput
  connect?: Prisma.CondominiumWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CondominiumUpdateToOneWithWhereWithoutEventsInput, Prisma.CondominiumUpdateWithoutEventsInput>, Prisma.CondominiumUncheckedUpdateWithoutEventsInput>
}

export type CondominiumCreateNestedOneWithoutIncidentsInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutIncidentsInput, Prisma.CondominiumUncheckedCreateWithoutIncidentsInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutIncidentsInput
  connect?: Prisma.CondominiumWhereUniqueInput
}

export type CondominiumUpdateOneRequiredWithoutIncidentsNestedInput = {
  create?: Prisma.XOR<Prisma.CondominiumCreateWithoutIncidentsInput, Prisma.CondominiumUncheckedCreateWithoutIncidentsInput>
  connectOrCreate?: Prisma.CondominiumCreateOrConnectWithoutIncidentsInput
  upsert?: Prisma.CondominiumUpsertWithoutIncidentsInput
  connect?: Prisma.CondominiumWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CondominiumUpdateToOneWithWhereWithoutIncidentsInput, Prisma.CondominiumUpdateWithoutIncidentsInput>, Prisma.CondominiumUncheckedUpdateWithoutIncidentsInput>
}

export type CondominiumCreateWithoutUsersInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  residents?: Prisma.ResidentCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordCreateNestedManyWithoutCondominiumInput
}

export type CondominiumUncheckedCreateWithoutUsersInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  residents?: Prisma.ResidentUncheckedCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorUncheckedCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderUncheckedCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationUncheckedCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordUncheckedCreateNestedManyWithoutCondominiumInput
}

export type CondominiumCreateOrConnectWithoutUsersInput = {
  where: Prisma.CondominiumWhereUniqueInput
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutUsersInput, Prisma.CondominiumUncheckedCreateWithoutUsersInput>
}

export type CondominiumUpsertWithoutUsersInput = {
  update: Prisma.XOR<Prisma.CondominiumUpdateWithoutUsersInput, Prisma.CondominiumUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutUsersInput, Prisma.CondominiumUncheckedCreateWithoutUsersInput>
  where?: Prisma.CondominiumWhereInput
}

export type CondominiumUpdateToOneWithWhereWithoutUsersInput = {
  where?: Prisma.CondominiumWhereInput
  data: Prisma.XOR<Prisma.CondominiumUpdateWithoutUsersInput, Prisma.CondominiumUncheckedUpdateWithoutUsersInput>
}

export type CondominiumUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  residents?: Prisma.ResidentUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  residents?: Prisma.ResidentUncheckedUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUncheckedUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUncheckedUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUncheckedUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUncheckedUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumCreateWithoutResidentsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordCreateNestedManyWithoutCondominiumInput
}

export type CondominiumUncheckedCreateWithoutResidentsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorUncheckedCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderUncheckedCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationUncheckedCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordUncheckedCreateNestedManyWithoutCondominiumInput
}

export type CondominiumCreateOrConnectWithoutResidentsInput = {
  where: Prisma.CondominiumWhereUniqueInput
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutResidentsInput, Prisma.CondominiumUncheckedCreateWithoutResidentsInput>
}

export type CondominiumUpsertWithoutResidentsInput = {
  update: Prisma.XOR<Prisma.CondominiumUpdateWithoutResidentsInput, Prisma.CondominiumUncheckedUpdateWithoutResidentsInput>
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutResidentsInput, Prisma.CondominiumUncheckedCreateWithoutResidentsInput>
  where?: Prisma.CondominiumWhereInput
}

export type CondominiumUpdateToOneWithWhereWithoutResidentsInput = {
  where?: Prisma.CondominiumWhereInput
  data: Prisma.XOR<Prisma.CondominiumUpdateWithoutResidentsInput, Prisma.CondominiumUncheckedUpdateWithoutResidentsInput>
}

export type CondominiumUpdateWithoutResidentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumUncheckedUpdateWithoutResidentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUncheckedUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUncheckedUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUncheckedUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUncheckedUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumCreateWithoutVisitorsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordCreateNestedManyWithoutCondominiumInput
}

export type CondominiumUncheckedCreateWithoutVisitorsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentUncheckedCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderUncheckedCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationUncheckedCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordUncheckedCreateNestedManyWithoutCondominiumInput
}

export type CondominiumCreateOrConnectWithoutVisitorsInput = {
  where: Prisma.CondominiumWhereUniqueInput
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutVisitorsInput, Prisma.CondominiumUncheckedCreateWithoutVisitorsInput>
}

export type CondominiumUpsertWithoutVisitorsInput = {
  update: Prisma.XOR<Prisma.CondominiumUpdateWithoutVisitorsInput, Prisma.CondominiumUncheckedUpdateWithoutVisitorsInput>
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutVisitorsInput, Prisma.CondominiumUncheckedCreateWithoutVisitorsInput>
  where?: Prisma.CondominiumWhereInput
}

export type CondominiumUpdateToOneWithWhereWithoutVisitorsInput = {
  where?: Prisma.CondominiumWhereInput
  data: Prisma.XOR<Prisma.CondominiumUpdateWithoutVisitorsInput, Prisma.CondominiumUncheckedUpdateWithoutVisitorsInput>
}

export type CondominiumUpdateWithoutVisitorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumUncheckedUpdateWithoutVisitorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUncheckedUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUncheckedUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUncheckedUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUncheckedUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumCreateWithoutServiceProvidersInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordCreateNestedManyWithoutCondominiumInput
}

export type CondominiumUncheckedCreateWithoutServiceProvidersInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentUncheckedCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorUncheckedCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationUncheckedCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordUncheckedCreateNestedManyWithoutCondominiumInput
}

export type CondominiumCreateOrConnectWithoutServiceProvidersInput = {
  where: Prisma.CondominiumWhereUniqueInput
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutServiceProvidersInput, Prisma.CondominiumUncheckedCreateWithoutServiceProvidersInput>
}

export type CondominiumUpsertWithoutServiceProvidersInput = {
  update: Prisma.XOR<Prisma.CondominiumUpdateWithoutServiceProvidersInput, Prisma.CondominiumUncheckedUpdateWithoutServiceProvidersInput>
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutServiceProvidersInput, Prisma.CondominiumUncheckedCreateWithoutServiceProvidersInput>
  where?: Prisma.CondominiumWhereInput
}

export type CondominiumUpdateToOneWithWhereWithoutServiceProvidersInput = {
  where?: Prisma.CondominiumWhereInput
  data: Prisma.XOR<Prisma.CondominiumUpdateWithoutServiceProvidersInput, Prisma.CondominiumUncheckedUpdateWithoutServiceProvidersInput>
}

export type CondominiumUpdateWithoutServiceProvidersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumUncheckedUpdateWithoutServiceProvidersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUncheckedUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUncheckedUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUncheckedUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUncheckedUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumCreateWithoutAuthorizationsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordCreateNestedManyWithoutCondominiumInput
}

export type CondominiumUncheckedCreateWithoutAuthorizationsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentUncheckedCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorUncheckedCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderUncheckedCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordUncheckedCreateNestedManyWithoutCondominiumInput
}

export type CondominiumCreateOrConnectWithoutAuthorizationsInput = {
  where: Prisma.CondominiumWhereUniqueInput
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutAuthorizationsInput, Prisma.CondominiumUncheckedCreateWithoutAuthorizationsInput>
}

export type CondominiumUpsertWithoutAuthorizationsInput = {
  update: Prisma.XOR<Prisma.CondominiumUpdateWithoutAuthorizationsInput, Prisma.CondominiumUncheckedUpdateWithoutAuthorizationsInput>
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutAuthorizationsInput, Prisma.CondominiumUncheckedCreateWithoutAuthorizationsInput>
  where?: Prisma.CondominiumWhereInput
}

export type CondominiumUpdateToOneWithWhereWithoutAuthorizationsInput = {
  where?: Prisma.CondominiumWhereInput
  data: Prisma.XOR<Prisma.CondominiumUpdateWithoutAuthorizationsInput, Prisma.CondominiumUncheckedUpdateWithoutAuthorizationsInput>
}

export type CondominiumUpdateWithoutAuthorizationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumUncheckedUpdateWithoutAuthorizationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUncheckedUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUncheckedUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUncheckedUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUncheckedUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumCreateWithoutAccessRecordsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationCreateNestedManyWithoutCondominiumInput
}

export type CondominiumUncheckedCreateWithoutAccessRecordsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentUncheckedCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorUncheckedCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderUncheckedCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationUncheckedCreateNestedManyWithoutCondominiumInput
}

export type CondominiumCreateOrConnectWithoutAccessRecordsInput = {
  where: Prisma.CondominiumWhereUniqueInput
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutAccessRecordsInput, Prisma.CondominiumUncheckedCreateWithoutAccessRecordsInput>
}

export type CondominiumUpsertWithoutAccessRecordsInput = {
  update: Prisma.XOR<Prisma.CondominiumUpdateWithoutAccessRecordsInput, Prisma.CondominiumUncheckedUpdateWithoutAccessRecordsInput>
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutAccessRecordsInput, Prisma.CondominiumUncheckedCreateWithoutAccessRecordsInput>
  where?: Prisma.CondominiumWhereInput
}

export type CondominiumUpdateToOneWithWhereWithoutAccessRecordsInput = {
  where?: Prisma.CondominiumWhereInput
  data: Prisma.XOR<Prisma.CondominiumUpdateWithoutAccessRecordsInput, Prisma.CondominiumUncheckedUpdateWithoutAccessRecordsInput>
}

export type CondominiumUpdateWithoutAccessRecordsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumUncheckedUpdateWithoutAccessRecordsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUncheckedUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUncheckedUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUncheckedUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUncheckedUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumCreateWithoutEventsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordCreateNestedManyWithoutCondominiumInput
}

export type CondominiumUncheckedCreateWithoutEventsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentUncheckedCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorUncheckedCreateNestedManyWithoutCondominiumInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderUncheckedCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationUncheckedCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordUncheckedCreateNestedManyWithoutCondominiumInput
}

export type CondominiumCreateOrConnectWithoutEventsInput = {
  where: Prisma.CondominiumWhereUniqueInput
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutEventsInput, Prisma.CondominiumUncheckedCreateWithoutEventsInput>
}

export type CondominiumUpsertWithoutEventsInput = {
  update: Prisma.XOR<Prisma.CondominiumUpdateWithoutEventsInput, Prisma.CondominiumUncheckedUpdateWithoutEventsInput>
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutEventsInput, Prisma.CondominiumUncheckedCreateWithoutEventsInput>
  where?: Prisma.CondominiumWhereInput
}

export type CondominiumUpdateToOneWithWhereWithoutEventsInput = {
  where?: Prisma.CondominiumWhereInput
  data: Prisma.XOR<Prisma.CondominiumUpdateWithoutEventsInput, Prisma.CondominiumUncheckedUpdateWithoutEventsInput>
}

export type CondominiumUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumUncheckedUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUncheckedUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUncheckedUpdateManyWithoutCondominiumNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUncheckedUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUncheckedUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUncheckedUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumCreateWithoutIncidentsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordCreateNestedManyWithoutCondominiumInput
}

export type CondominiumUncheckedCreateWithoutIncidentsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutCondominiumInput
  residents?: Prisma.ResidentUncheckedCreateNestedManyWithoutCondominiumInput
  visitors?: Prisma.VisitorUncheckedCreateNestedManyWithoutCondominiumInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutCondominiumInput
  serviceProviders?: Prisma.ServiceProviderUncheckedCreateNestedManyWithoutCondominiumInput
  authorizations?: Prisma.AuthorizationUncheckedCreateNestedManyWithoutCondominiumInput
  accessRecords?: Prisma.AccessRecordUncheckedCreateNestedManyWithoutCondominiumInput
}

export type CondominiumCreateOrConnectWithoutIncidentsInput = {
  where: Prisma.CondominiumWhereUniqueInput
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutIncidentsInput, Prisma.CondominiumUncheckedCreateWithoutIncidentsInput>
}

export type CondominiumUpsertWithoutIncidentsInput = {
  update: Prisma.XOR<Prisma.CondominiumUpdateWithoutIncidentsInput, Prisma.CondominiumUncheckedUpdateWithoutIncidentsInput>
  create: Prisma.XOR<Prisma.CondominiumCreateWithoutIncidentsInput, Prisma.CondominiumUncheckedCreateWithoutIncidentsInput>
  where?: Prisma.CondominiumWhereInput
}

export type CondominiumUpdateToOneWithWhereWithoutIncidentsInput = {
  where?: Prisma.CondominiumWhereInput
  data: Prisma.XOR<Prisma.CondominiumUpdateWithoutIncidentsInput, Prisma.CondominiumUncheckedUpdateWithoutIncidentsInput>
}

export type CondominiumUpdateWithoutIncidentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUpdateManyWithoutCondominiumNestedInput
}

export type CondominiumUncheckedUpdateWithoutIncidentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutCondominiumNestedInput
  residents?: Prisma.ResidentUncheckedUpdateManyWithoutCondominiumNestedInput
  visitors?: Prisma.VisitorUncheckedUpdateManyWithoutCondominiumNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutCondominiumNestedInput
  serviceProviders?: Prisma.ServiceProviderUncheckedUpdateManyWithoutCondominiumNestedInput
  authorizations?: Prisma.AuthorizationUncheckedUpdateManyWithoutCondominiumNestedInput
  accessRecords?: Prisma.AccessRecordUncheckedUpdateManyWithoutCondominiumNestedInput
}


/**
 * Count Type CondominiumCountOutputType
 */

export type CondominiumCountOutputType = {
  users: number
  residents: number
  visitors: number
  events: number
  incidents: number
  serviceProviders: number
  authorizations: number
  accessRecords: number
}

export type CondominiumCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | CondominiumCountOutputTypeCountUsersArgs
  residents?: boolean | CondominiumCountOutputTypeCountResidentsArgs
  visitors?: boolean | CondominiumCountOutputTypeCountVisitorsArgs
  events?: boolean | CondominiumCountOutputTypeCountEventsArgs
  incidents?: boolean | CondominiumCountOutputTypeCountIncidentsArgs
  serviceProviders?: boolean | CondominiumCountOutputTypeCountServiceProvidersArgs
  authorizations?: boolean | CondominiumCountOutputTypeCountAuthorizationsArgs
  accessRecords?: boolean | CondominiumCountOutputTypeCountAccessRecordsArgs
}

/**
 * CondominiumCountOutputType without action
 */
export type CondominiumCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CondominiumCountOutputType
   */
  select?: Prisma.CondominiumCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CondominiumCountOutputType without action
 */
export type CondominiumCountOutputTypeCountUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
}

/**
 * CondominiumCountOutputType without action
 */
export type CondominiumCountOutputTypeCountResidentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ResidentWhereInput
}

/**
 * CondominiumCountOutputType without action
 */
export type CondominiumCountOutputTypeCountVisitorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VisitorWhereInput
}

/**
 * CondominiumCountOutputType without action
 */
export type CondominiumCountOutputTypeCountEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventWhereInput
}

/**
 * CondominiumCountOutputType without action
 */
export type CondominiumCountOutputTypeCountIncidentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IncidentWhereInput
}

/**
 * CondominiumCountOutputType without action
 */
export type CondominiumCountOutputTypeCountServiceProvidersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceProviderWhereInput
}

/**
 * CondominiumCountOutputType without action
 */
export type CondominiumCountOutputTypeCountAuthorizationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuthorizationWhereInput
}

/**
 * CondominiumCountOutputType without action
 */
export type CondominiumCountOutputTypeCountAccessRecordsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccessRecordWhereInput
}


export type CondominiumSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  users?: boolean | Prisma.Condominium$usersArgs<ExtArgs>
  residents?: boolean | Prisma.Condominium$residentsArgs<ExtArgs>
  visitors?: boolean | Prisma.Condominium$visitorsArgs<ExtArgs>
  events?: boolean | Prisma.Condominium$eventsArgs<ExtArgs>
  incidents?: boolean | Prisma.Condominium$incidentsArgs<ExtArgs>
  serviceProviders?: boolean | Prisma.Condominium$serviceProvidersArgs<ExtArgs>
  authorizations?: boolean | Prisma.Condominium$authorizationsArgs<ExtArgs>
  accessRecords?: boolean | Prisma.Condominium$accessRecordsArgs<ExtArgs>
  _count?: boolean | Prisma.CondominiumCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["condominium"]>

export type CondominiumSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["condominium"]>

export type CondominiumSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["condominium"]>

export type CondominiumSelectScalar = {
  id?: boolean
  name?: boolean
  slug?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CondominiumOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "slug" | "createdAt" | "updatedAt", ExtArgs["result"]["condominium"]>
export type CondominiumInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.Condominium$usersArgs<ExtArgs>
  residents?: boolean | Prisma.Condominium$residentsArgs<ExtArgs>
  visitors?: boolean | Prisma.Condominium$visitorsArgs<ExtArgs>
  events?: boolean | Prisma.Condominium$eventsArgs<ExtArgs>
  incidents?: boolean | Prisma.Condominium$incidentsArgs<ExtArgs>
  serviceProviders?: boolean | Prisma.Condominium$serviceProvidersArgs<ExtArgs>
  authorizations?: boolean | Prisma.Condominium$authorizationsArgs<ExtArgs>
  accessRecords?: boolean | Prisma.Condominium$accessRecordsArgs<ExtArgs>
  _count?: boolean | Prisma.CondominiumCountOutputTypeDefaultArgs<ExtArgs>
}
export type CondominiumIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CondominiumIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CondominiumPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Condominium"
  objects: {
    users: Prisma.$UserPayload<ExtArgs>[]
    residents: Prisma.$ResidentPayload<ExtArgs>[]
    visitors: Prisma.$VisitorPayload<ExtArgs>[]
    events: Prisma.$EventPayload<ExtArgs>[]
    incidents: Prisma.$IncidentPayload<ExtArgs>[]
    serviceProviders: Prisma.$ServiceProviderPayload<ExtArgs>[]
    authorizations: Prisma.$AuthorizationPayload<ExtArgs>[]
    accessRecords: Prisma.$AccessRecordPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    slug: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["condominium"]>
  composites: {}
}

export type CondominiumGetPayload<S extends boolean | null | undefined | CondominiumDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CondominiumPayload, S>

export type CondominiumCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CondominiumFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CondominiumCountAggregateInputType | true
  }

export interface CondominiumDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Condominium'], meta: { name: 'Condominium' } }
  /**
   * Find zero or one Condominium that matches the filter.
   * @param {CondominiumFindUniqueArgs} args - Arguments to find a Condominium
   * @example
   * // Get one Condominium
   * const condominium = await prisma.condominium.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CondominiumFindUniqueArgs>(args: Prisma.SelectSubset<T, CondominiumFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CondominiumClient<runtime.Types.Result.GetResult<Prisma.$CondominiumPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Condominium that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CondominiumFindUniqueOrThrowArgs} args - Arguments to find a Condominium
   * @example
   * // Get one Condominium
   * const condominium = await prisma.condominium.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CondominiumFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CondominiumFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CondominiumClient<runtime.Types.Result.GetResult<Prisma.$CondominiumPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Condominium that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CondominiumFindFirstArgs} args - Arguments to find a Condominium
   * @example
   * // Get one Condominium
   * const condominium = await prisma.condominium.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CondominiumFindFirstArgs>(args?: Prisma.SelectSubset<T, CondominiumFindFirstArgs<ExtArgs>>): Prisma.Prisma__CondominiumClient<runtime.Types.Result.GetResult<Prisma.$CondominiumPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Condominium that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CondominiumFindFirstOrThrowArgs} args - Arguments to find a Condominium
   * @example
   * // Get one Condominium
   * const condominium = await prisma.condominium.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CondominiumFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CondominiumFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CondominiumClient<runtime.Types.Result.GetResult<Prisma.$CondominiumPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Condominiums that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CondominiumFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Condominiums
   * const condominiums = await prisma.condominium.findMany()
   * 
   * // Get first 10 Condominiums
   * const condominiums = await prisma.condominium.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const condominiumWithIdOnly = await prisma.condominium.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CondominiumFindManyArgs>(args?: Prisma.SelectSubset<T, CondominiumFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CondominiumPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Condominium.
   * @param {CondominiumCreateArgs} args - Arguments to create a Condominium.
   * @example
   * // Create one Condominium
   * const Condominium = await prisma.condominium.create({
   *   data: {
   *     // ... data to create a Condominium
   *   }
   * })
   * 
   */
  create<T extends CondominiumCreateArgs>(args: Prisma.SelectSubset<T, CondominiumCreateArgs<ExtArgs>>): Prisma.Prisma__CondominiumClient<runtime.Types.Result.GetResult<Prisma.$CondominiumPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Condominiums.
   * @param {CondominiumCreateManyArgs} args - Arguments to create many Condominiums.
   * @example
   * // Create many Condominiums
   * const condominium = await prisma.condominium.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CondominiumCreateManyArgs>(args?: Prisma.SelectSubset<T, CondominiumCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Condominiums and returns the data saved in the database.
   * @param {CondominiumCreateManyAndReturnArgs} args - Arguments to create many Condominiums.
   * @example
   * // Create many Condominiums
   * const condominium = await prisma.condominium.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Condominiums and only return the `id`
   * const condominiumWithIdOnly = await prisma.condominium.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CondominiumCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CondominiumCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CondominiumPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Condominium.
   * @param {CondominiumDeleteArgs} args - Arguments to delete one Condominium.
   * @example
   * // Delete one Condominium
   * const Condominium = await prisma.condominium.delete({
   *   where: {
   *     // ... filter to delete one Condominium
   *   }
   * })
   * 
   */
  delete<T extends CondominiumDeleteArgs>(args: Prisma.SelectSubset<T, CondominiumDeleteArgs<ExtArgs>>): Prisma.Prisma__CondominiumClient<runtime.Types.Result.GetResult<Prisma.$CondominiumPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Condominium.
   * @param {CondominiumUpdateArgs} args - Arguments to update one Condominium.
   * @example
   * // Update one Condominium
   * const condominium = await prisma.condominium.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CondominiumUpdateArgs>(args: Prisma.SelectSubset<T, CondominiumUpdateArgs<ExtArgs>>): Prisma.Prisma__CondominiumClient<runtime.Types.Result.GetResult<Prisma.$CondominiumPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Condominiums.
   * @param {CondominiumDeleteManyArgs} args - Arguments to filter Condominiums to delete.
   * @example
   * // Delete a few Condominiums
   * const { count } = await prisma.condominium.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CondominiumDeleteManyArgs>(args?: Prisma.SelectSubset<T, CondominiumDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Condominiums.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CondominiumUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Condominiums
   * const condominium = await prisma.condominium.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CondominiumUpdateManyArgs>(args: Prisma.SelectSubset<T, CondominiumUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Condominiums and returns the data updated in the database.
   * @param {CondominiumUpdateManyAndReturnArgs} args - Arguments to update many Condominiums.
   * @example
   * // Update many Condominiums
   * const condominium = await prisma.condominium.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Condominiums and only return the `id`
   * const condominiumWithIdOnly = await prisma.condominium.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CondominiumUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CondominiumUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CondominiumPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Condominium.
   * @param {CondominiumUpsertArgs} args - Arguments to update or create a Condominium.
   * @example
   * // Update or create a Condominium
   * const condominium = await prisma.condominium.upsert({
   *   create: {
   *     // ... data to create a Condominium
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Condominium we want to update
   *   }
   * })
   */
  upsert<T extends CondominiumUpsertArgs>(args: Prisma.SelectSubset<T, CondominiumUpsertArgs<ExtArgs>>): Prisma.Prisma__CondominiumClient<runtime.Types.Result.GetResult<Prisma.$CondominiumPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Condominiums.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CondominiumCountArgs} args - Arguments to filter Condominiums to count.
   * @example
   * // Count the number of Condominiums
   * const count = await prisma.condominium.count({
   *   where: {
   *     // ... the filter for the Condominiums we want to count
   *   }
   * })
  **/
  count<T extends CondominiumCountArgs>(
    args?: Prisma.Subset<T, CondominiumCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CondominiumCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Condominium.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CondominiumAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CondominiumAggregateArgs>(args: Prisma.Subset<T, CondominiumAggregateArgs>): Prisma.PrismaPromise<GetCondominiumAggregateType<T>>

  /**
   * Group by Condominium.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CondominiumGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CondominiumGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CondominiumGroupByArgs['orderBy'] }
      : { orderBy?: CondominiumGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CondominiumGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCondominiumGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Condominium model
 */
readonly fields: CondominiumFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Condominium.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CondominiumClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.Condominium$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Condominium$usersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  residents<T extends Prisma.Condominium$residentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Condominium$residentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ResidentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  visitors<T extends Prisma.Condominium$visitorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Condominium$visitorsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VisitorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  events<T extends Prisma.Condominium$eventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Condominium$eventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  incidents<T extends Prisma.Condominium$incidentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Condominium$incidentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  serviceProviders<T extends Prisma.Condominium$serviceProvidersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Condominium$serviceProvidersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceProviderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  authorizations<T extends Prisma.Condominium$authorizationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Condominium$authorizationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthorizationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  accessRecords<T extends Prisma.Condominium$accessRecordsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Condominium$accessRecordsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccessRecordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Condominium model
 */
export interface CondominiumFieldRefs {
  readonly id: Prisma.FieldRef<"Condominium", 'String'>
  readonly name: Prisma.FieldRef<"Condominium", 'String'>
  readonly slug: Prisma.FieldRef<"Condominium", 'String'>
  readonly createdAt: Prisma.FieldRef<"Condominium", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Condominium", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Condominium findUnique
 */
export type CondominiumFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Condominium
   */
  select?: Prisma.CondominiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Condominium
   */
  omit?: Prisma.CondominiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CondominiumInclude<ExtArgs> | null
  /**
   * Filter, which Condominium to fetch.
   */
  where: Prisma.CondominiumWhereUniqueInput
}

/**
 * Condominium findUniqueOrThrow
 */
export type CondominiumFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Condominium
   */
  select?: Prisma.CondominiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Condominium
   */
  omit?: Prisma.CondominiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CondominiumInclude<ExtArgs> | null
  /**
   * Filter, which Condominium to fetch.
   */
  where: Prisma.CondominiumWhereUniqueInput
}

/**
 * Condominium findFirst
 */
export type CondominiumFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Condominium
   */
  select?: Prisma.CondominiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Condominium
   */
  omit?: Prisma.CondominiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CondominiumInclude<ExtArgs> | null
  /**
   * Filter, which Condominium to fetch.
   */
  where?: Prisma.CondominiumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Condominiums to fetch.
   */
  orderBy?: Prisma.CondominiumOrderByWithRelationInput | Prisma.CondominiumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Condominiums.
   */
  cursor?: Prisma.CondominiumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Condominiums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Condominiums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Condominiums.
   */
  distinct?: Prisma.CondominiumScalarFieldEnum | Prisma.CondominiumScalarFieldEnum[]
}

/**
 * Condominium findFirstOrThrow
 */
export type CondominiumFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Condominium
   */
  select?: Prisma.CondominiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Condominium
   */
  omit?: Prisma.CondominiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CondominiumInclude<ExtArgs> | null
  /**
   * Filter, which Condominium to fetch.
   */
  where?: Prisma.CondominiumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Condominiums to fetch.
   */
  orderBy?: Prisma.CondominiumOrderByWithRelationInput | Prisma.CondominiumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Condominiums.
   */
  cursor?: Prisma.CondominiumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Condominiums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Condominiums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Condominiums.
   */
  distinct?: Prisma.CondominiumScalarFieldEnum | Prisma.CondominiumScalarFieldEnum[]
}

/**
 * Condominium findMany
 */
export type CondominiumFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Condominium
   */
  select?: Prisma.CondominiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Condominium
   */
  omit?: Prisma.CondominiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CondominiumInclude<ExtArgs> | null
  /**
   * Filter, which Condominiums to fetch.
   */
  where?: Prisma.CondominiumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Condominiums to fetch.
   */
  orderBy?: Prisma.CondominiumOrderByWithRelationInput | Prisma.CondominiumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Condominiums.
   */
  cursor?: Prisma.CondominiumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Condominiums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Condominiums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Condominiums.
   */
  distinct?: Prisma.CondominiumScalarFieldEnum | Prisma.CondominiumScalarFieldEnum[]
}

/**
 * Condominium create
 */
export type CondominiumCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Condominium
   */
  select?: Prisma.CondominiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Condominium
   */
  omit?: Prisma.CondominiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CondominiumInclude<ExtArgs> | null
  /**
   * The data needed to create a Condominium.
   */
  data: Prisma.XOR<Prisma.CondominiumCreateInput, Prisma.CondominiumUncheckedCreateInput>
}

/**
 * Condominium createMany
 */
export type CondominiumCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Condominiums.
   */
  data: Prisma.CondominiumCreateManyInput | Prisma.CondominiumCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Condominium createManyAndReturn
 */
export type CondominiumCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Condominium
   */
  select?: Prisma.CondominiumSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Condominium
   */
  omit?: Prisma.CondominiumOmit<ExtArgs> | null
  /**
   * The data used to create many Condominiums.
   */
  data: Prisma.CondominiumCreateManyInput | Prisma.CondominiumCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Condominium update
 */
export type CondominiumUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Condominium
   */
  select?: Prisma.CondominiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Condominium
   */
  omit?: Prisma.CondominiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CondominiumInclude<ExtArgs> | null
  /**
   * The data needed to update a Condominium.
   */
  data: Prisma.XOR<Prisma.CondominiumUpdateInput, Prisma.CondominiumUncheckedUpdateInput>
  /**
   * Choose, which Condominium to update.
   */
  where: Prisma.CondominiumWhereUniqueInput
}

/**
 * Condominium updateMany
 */
export type CondominiumUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Condominiums.
   */
  data: Prisma.XOR<Prisma.CondominiumUpdateManyMutationInput, Prisma.CondominiumUncheckedUpdateManyInput>
  /**
   * Filter which Condominiums to update
   */
  where?: Prisma.CondominiumWhereInput
  /**
   * Limit how many Condominiums to update.
   */
  limit?: number
}

/**
 * Condominium updateManyAndReturn
 */
export type CondominiumUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Condominium
   */
  select?: Prisma.CondominiumSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Condominium
   */
  omit?: Prisma.CondominiumOmit<ExtArgs> | null
  /**
   * The data used to update Condominiums.
   */
  data: Prisma.XOR<Prisma.CondominiumUpdateManyMutationInput, Prisma.CondominiumUncheckedUpdateManyInput>
  /**
   * Filter which Condominiums to update
   */
  where?: Prisma.CondominiumWhereInput
  /**
   * Limit how many Condominiums to update.
   */
  limit?: number
}

/**
 * Condominium upsert
 */
export type CondominiumUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Condominium
   */
  select?: Prisma.CondominiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Condominium
   */
  omit?: Prisma.CondominiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CondominiumInclude<ExtArgs> | null
  /**
   * The filter to search for the Condominium to update in case it exists.
   */
  where: Prisma.CondominiumWhereUniqueInput
  /**
   * In case the Condominium found by the `where` argument doesn't exist, create a new Condominium with this data.
   */
  create: Prisma.XOR<Prisma.CondominiumCreateInput, Prisma.CondominiumUncheckedCreateInput>
  /**
   * In case the Condominium was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CondominiumUpdateInput, Prisma.CondominiumUncheckedUpdateInput>
}

/**
 * Condominium delete
 */
export type CondominiumDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Condominium
   */
  select?: Prisma.CondominiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Condominium
   */
  omit?: Prisma.CondominiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CondominiumInclude<ExtArgs> | null
  /**
   * Filter which Condominium to delete.
   */
  where: Prisma.CondominiumWhereUniqueInput
}

/**
 * Condominium deleteMany
 */
export type CondominiumDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Condominiums to delete
   */
  where?: Prisma.CondominiumWhereInput
  /**
   * Limit how many Condominiums to delete.
   */
  limit?: number
}

/**
 * Condominium.users
 */
export type Condominium$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  cursor?: Prisma.UserWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * Condominium.residents
 */
export type Condominium$residentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Resident
   */
  select?: Prisma.ResidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Resident
   */
  omit?: Prisma.ResidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResidentInclude<ExtArgs> | null
  where?: Prisma.ResidentWhereInput
  orderBy?: Prisma.ResidentOrderByWithRelationInput | Prisma.ResidentOrderByWithRelationInput[]
  cursor?: Prisma.ResidentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ResidentScalarFieldEnum | Prisma.ResidentScalarFieldEnum[]
}

/**
 * Condominium.visitors
 */
export type Condominium$visitorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Visitor
   */
  select?: Prisma.VisitorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Visitor
   */
  omit?: Prisma.VisitorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitorInclude<ExtArgs> | null
  where?: Prisma.VisitorWhereInput
  orderBy?: Prisma.VisitorOrderByWithRelationInput | Prisma.VisitorOrderByWithRelationInput[]
  cursor?: Prisma.VisitorWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VisitorScalarFieldEnum | Prisma.VisitorScalarFieldEnum[]
}

/**
 * Condominium.events
 */
export type Condominium$eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Event
   */
  select?: Prisma.EventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Event
   */
  omit?: Prisma.EventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventInclude<ExtArgs> | null
  where?: Prisma.EventWhereInput
  orderBy?: Prisma.EventOrderByWithRelationInput | Prisma.EventOrderByWithRelationInput[]
  cursor?: Prisma.EventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EventScalarFieldEnum | Prisma.EventScalarFieldEnum[]
}

/**
 * Condominium.incidents
 */
export type Condominium$incidentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
  where?: Prisma.IncidentWhereInput
  orderBy?: Prisma.IncidentOrderByWithRelationInput | Prisma.IncidentOrderByWithRelationInput[]
  cursor?: Prisma.IncidentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.IncidentScalarFieldEnum | Prisma.IncidentScalarFieldEnum[]
}

/**
 * Condominium.serviceProviders
 */
export type Condominium$serviceProvidersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProvider
   */
  select?: Prisma.ServiceProviderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProvider
   */
  omit?: Prisma.ServiceProviderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderInclude<ExtArgs> | null
  where?: Prisma.ServiceProviderWhereInput
  orderBy?: Prisma.ServiceProviderOrderByWithRelationInput | Prisma.ServiceProviderOrderByWithRelationInput[]
  cursor?: Prisma.ServiceProviderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ServiceProviderScalarFieldEnum | Prisma.ServiceProviderScalarFieldEnum[]
}

/**
 * Condominium.authorizations
 */
export type Condominium$authorizationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Authorization
   */
  select?: Prisma.AuthorizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Authorization
   */
  omit?: Prisma.AuthorizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInclude<ExtArgs> | null
  where?: Prisma.AuthorizationWhereInput
  orderBy?: Prisma.AuthorizationOrderByWithRelationInput | Prisma.AuthorizationOrderByWithRelationInput[]
  cursor?: Prisma.AuthorizationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AuthorizationScalarFieldEnum | Prisma.AuthorizationScalarFieldEnum[]
}

/**
 * Condominium.accessRecords
 */
export type Condominium$accessRecordsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRecord
   */
  select?: Prisma.AccessRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRecord
   */
  omit?: Prisma.AccessRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRecordInclude<ExtArgs> | null
  where?: Prisma.AccessRecordWhereInput
  orderBy?: Prisma.AccessRecordOrderByWithRelationInput | Prisma.AccessRecordOrderByWithRelationInput[]
  cursor?: Prisma.AccessRecordWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AccessRecordScalarFieldEnum | Prisma.AccessRecordScalarFieldEnum[]
}

/**
 * Condominium without action
 */
export type CondominiumDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Condominium
   */
  select?: Prisma.CondominiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Condominium
   */
  omit?: Prisma.CondominiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CondominiumInclude<ExtArgs> | null
}
