
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EventGuest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model EventGuest
 * 
 */
export type EventGuestModel = runtime.Types.Result.DefaultSelection<Prisma.$EventGuestPayload>

export type AggregateEventGuest = {
  _count: EventGuestCountAggregateOutputType | null
  _min: EventGuestMinAggregateOutputType | null
  _max: EventGuestMaxAggregateOutputType | null
}

export type EventGuestMinAggregateOutputType = {
  id: string | null
  eventId: string | null
  name: string | null
  documentEncrypted: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EventGuestMaxAggregateOutputType = {
  id: string | null
  eventId: string | null
  name: string | null
  documentEncrypted: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EventGuestCountAggregateOutputType = {
  id: number
  eventId: number
  name: number
  documentEncrypted: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type EventGuestMinAggregateInputType = {
  id?: true
  eventId?: true
  name?: true
  documentEncrypted?: true
  createdAt?: true
  updatedAt?: true
}

export type EventGuestMaxAggregateInputType = {
  id?: true
  eventId?: true
  name?: true
  documentEncrypted?: true
  createdAt?: true
  updatedAt?: true
}

export type EventGuestCountAggregateInputType = {
  id?: true
  eventId?: true
  name?: true
  documentEncrypted?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type EventGuestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventGuest to aggregate.
   */
  where?: Prisma.EventGuestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventGuests to fetch.
   */
  orderBy?: Prisma.EventGuestOrderByWithRelationInput | Prisma.EventGuestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventGuestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventGuests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventGuests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventGuests
  **/
  _count?: true | EventGuestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventGuestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventGuestMaxAggregateInputType
}

export type GetEventGuestAggregateType<T extends EventGuestAggregateArgs> = {
      [P in keyof T & keyof AggregateEventGuest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventGuest[P]>
    : Prisma.GetScalarType<T[P], AggregateEventGuest[P]>
}




export type EventGuestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventGuestWhereInput
  orderBy?: Prisma.EventGuestOrderByWithAggregationInput | Prisma.EventGuestOrderByWithAggregationInput[]
  by: Prisma.EventGuestScalarFieldEnum[] | Prisma.EventGuestScalarFieldEnum
  having?: Prisma.EventGuestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventGuestCountAggregateInputType | true
  _min?: EventGuestMinAggregateInputType
  _max?: EventGuestMaxAggregateInputType
}

export type EventGuestGroupByOutputType = {
  id: string
  eventId: string
  name: string
  documentEncrypted: string | null
  createdAt: Date
  updatedAt: Date
  _count: EventGuestCountAggregateOutputType | null
  _min: EventGuestMinAggregateOutputType | null
  _max: EventGuestMaxAggregateOutputType | null
}

export type GetEventGuestGroupByPayload<T extends EventGuestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventGuestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventGuestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventGuestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventGuestGroupByOutputType[P]>
      }
    >
  >



export type EventGuestWhereInput = {
  AND?: Prisma.EventGuestWhereInput | Prisma.EventGuestWhereInput[]
  OR?: Prisma.EventGuestWhereInput[]
  NOT?: Prisma.EventGuestWhereInput | Prisma.EventGuestWhereInput[]
  id?: Prisma.StringFilter<"EventGuest"> | string
  eventId?: Prisma.StringFilter<"EventGuest"> | string
  name?: Prisma.StringFilter<"EventGuest"> | string
  documentEncrypted?: Prisma.StringNullableFilter<"EventGuest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventGuest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventGuest"> | Date | string
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
}

export type EventGuestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  documentEncrypted?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  event?: Prisma.EventOrderByWithRelationInput
}

export type EventGuestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EventGuestWhereInput | Prisma.EventGuestWhereInput[]
  OR?: Prisma.EventGuestWhereInput[]
  NOT?: Prisma.EventGuestWhereInput | Prisma.EventGuestWhereInput[]
  eventId?: Prisma.StringFilter<"EventGuest"> | string
  name?: Prisma.StringFilter<"EventGuest"> | string
  documentEncrypted?: Prisma.StringNullableFilter<"EventGuest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventGuest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventGuest"> | Date | string
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
}, "id">

export type EventGuestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  documentEncrypted?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.EventGuestCountOrderByAggregateInput
  _max?: Prisma.EventGuestMaxOrderByAggregateInput
  _min?: Prisma.EventGuestMinOrderByAggregateInput
}

export type EventGuestScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventGuestScalarWhereWithAggregatesInput | Prisma.EventGuestScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventGuestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventGuestScalarWhereWithAggregatesInput | Prisma.EventGuestScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EventGuest"> | string
  eventId?: Prisma.StringWithAggregatesFilter<"EventGuest"> | string
  name?: Prisma.StringWithAggregatesFilter<"EventGuest"> | string
  documentEncrypted?: Prisma.StringNullableWithAggregatesFilter<"EventGuest"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EventGuest"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EventGuest"> | Date | string
}

export type EventGuestCreateInput = {
  id?: string
  name: string
  documentEncrypted?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  event: Prisma.EventCreateNestedOneWithoutGuestsInput
}

export type EventGuestUncheckedCreateInput = {
  id?: string
  eventId: string
  name: string
  documentEncrypted?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventGuestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  documentEncrypted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  event?: Prisma.EventUpdateOneRequiredWithoutGuestsNestedInput
}

export type EventGuestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  documentEncrypted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventGuestCreateManyInput = {
  id?: string
  eventId: string
  name: string
  documentEncrypted?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventGuestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  documentEncrypted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventGuestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  documentEncrypted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventGuestListRelationFilter = {
  every?: Prisma.EventGuestWhereInput
  some?: Prisma.EventGuestWhereInput
  none?: Prisma.EventGuestWhereInput
}

export type EventGuestOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EventGuestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  documentEncrypted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventGuestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  documentEncrypted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventGuestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  documentEncrypted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventGuestCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventGuestCreateWithoutEventInput, Prisma.EventGuestUncheckedCreateWithoutEventInput> | Prisma.EventGuestCreateWithoutEventInput[] | Prisma.EventGuestUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventGuestCreateOrConnectWithoutEventInput | Prisma.EventGuestCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventGuestCreateManyEventInputEnvelope
  connect?: Prisma.EventGuestWhereUniqueInput | Prisma.EventGuestWhereUniqueInput[]
}

export type EventGuestUncheckedCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventGuestCreateWithoutEventInput, Prisma.EventGuestUncheckedCreateWithoutEventInput> | Prisma.EventGuestCreateWithoutEventInput[] | Prisma.EventGuestUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventGuestCreateOrConnectWithoutEventInput | Prisma.EventGuestCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventGuestCreateManyEventInputEnvelope
  connect?: Prisma.EventGuestWhereUniqueInput | Prisma.EventGuestWhereUniqueInput[]
}

export type EventGuestUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventGuestCreateWithoutEventInput, Prisma.EventGuestUncheckedCreateWithoutEventInput> | Prisma.EventGuestCreateWithoutEventInput[] | Prisma.EventGuestUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventGuestCreateOrConnectWithoutEventInput | Prisma.EventGuestCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventGuestUpsertWithWhereUniqueWithoutEventInput | Prisma.EventGuestUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventGuestCreateManyEventInputEnvelope
  set?: Prisma.EventGuestWhereUniqueInput | Prisma.EventGuestWhereUniqueInput[]
  disconnect?: Prisma.EventGuestWhereUniqueInput | Prisma.EventGuestWhereUniqueInput[]
  delete?: Prisma.EventGuestWhereUniqueInput | Prisma.EventGuestWhereUniqueInput[]
  connect?: Prisma.EventGuestWhereUniqueInput | Prisma.EventGuestWhereUniqueInput[]
  update?: Prisma.EventGuestUpdateWithWhereUniqueWithoutEventInput | Prisma.EventGuestUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventGuestUpdateManyWithWhereWithoutEventInput | Prisma.EventGuestUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventGuestScalarWhereInput | Prisma.EventGuestScalarWhereInput[]
}

export type EventGuestUncheckedUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventGuestCreateWithoutEventInput, Prisma.EventGuestUncheckedCreateWithoutEventInput> | Prisma.EventGuestCreateWithoutEventInput[] | Prisma.EventGuestUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventGuestCreateOrConnectWithoutEventInput | Prisma.EventGuestCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventGuestUpsertWithWhereUniqueWithoutEventInput | Prisma.EventGuestUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventGuestCreateManyEventInputEnvelope
  set?: Prisma.EventGuestWhereUniqueInput | Prisma.EventGuestWhereUniqueInput[]
  disconnect?: Prisma.EventGuestWhereUniqueInput | Prisma.EventGuestWhereUniqueInput[]
  delete?: Prisma.EventGuestWhereUniqueInput | Prisma.EventGuestWhereUniqueInput[]
  connect?: Prisma.EventGuestWhereUniqueInput | Prisma.EventGuestWhereUniqueInput[]
  update?: Prisma.EventGuestUpdateWithWhereUniqueWithoutEventInput | Prisma.EventGuestUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventGuestUpdateManyWithWhereWithoutEventInput | Prisma.EventGuestUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventGuestScalarWhereInput | Prisma.EventGuestScalarWhereInput[]
}

export type EventGuestCreateWithoutEventInput = {
  id?: string
  name: string
  documentEncrypted?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventGuestUncheckedCreateWithoutEventInput = {
  id?: string
  name: string
  documentEncrypted?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventGuestCreateOrConnectWithoutEventInput = {
  where: Prisma.EventGuestWhereUniqueInput
  create: Prisma.XOR<Prisma.EventGuestCreateWithoutEventInput, Prisma.EventGuestUncheckedCreateWithoutEventInput>
}

export type EventGuestCreateManyEventInputEnvelope = {
  data: Prisma.EventGuestCreateManyEventInput | Prisma.EventGuestCreateManyEventInput[]
  skipDuplicates?: boolean
}

export type EventGuestUpsertWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventGuestWhereUniqueInput
  update: Prisma.XOR<Prisma.EventGuestUpdateWithoutEventInput, Prisma.EventGuestUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.EventGuestCreateWithoutEventInput, Prisma.EventGuestUncheckedCreateWithoutEventInput>
}

export type EventGuestUpdateWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventGuestWhereUniqueInput
  data: Prisma.XOR<Prisma.EventGuestUpdateWithoutEventInput, Prisma.EventGuestUncheckedUpdateWithoutEventInput>
}

export type EventGuestUpdateManyWithWhereWithoutEventInput = {
  where: Prisma.EventGuestScalarWhereInput
  data: Prisma.XOR<Prisma.EventGuestUpdateManyMutationInput, Prisma.EventGuestUncheckedUpdateManyWithoutEventInput>
}

export type EventGuestScalarWhereInput = {
  AND?: Prisma.EventGuestScalarWhereInput | Prisma.EventGuestScalarWhereInput[]
  OR?: Prisma.EventGuestScalarWhereInput[]
  NOT?: Prisma.EventGuestScalarWhereInput | Prisma.EventGuestScalarWhereInput[]
  id?: Prisma.StringFilter<"EventGuest"> | string
  eventId?: Prisma.StringFilter<"EventGuest"> | string
  name?: Prisma.StringFilter<"EventGuest"> | string
  documentEncrypted?: Prisma.StringNullableFilter<"EventGuest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventGuest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventGuest"> | Date | string
}

export type EventGuestCreateManyEventInput = {
  id?: string
  name: string
  documentEncrypted?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventGuestUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  documentEncrypted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventGuestUncheckedUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  documentEncrypted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventGuestUncheckedUpdateManyWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  documentEncrypted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type EventGuestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  name?: boolean
  documentEncrypted?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventGuest"]>

export type EventGuestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  name?: boolean
  documentEncrypted?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventGuest"]>

export type EventGuestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  name?: boolean
  documentEncrypted?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventGuest"]>

export type EventGuestSelectScalar = {
  id?: boolean
  eventId?: boolean
  name?: boolean
  documentEncrypted?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type EventGuestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "eventId" | "name" | "documentEncrypted" | "createdAt" | "updatedAt", ExtArgs["result"]["eventGuest"]>
export type EventGuestInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}
export type EventGuestIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}
export type EventGuestIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}

export type $EventGuestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventGuest"
  objects: {
    event: Prisma.$EventPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    eventId: string
    name: string
    documentEncrypted: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["eventGuest"]>
  composites: {}
}

export type EventGuestGetPayload<S extends boolean | null | undefined | EventGuestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventGuestPayload, S>

export type EventGuestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventGuestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventGuestCountAggregateInputType | true
  }

export interface EventGuestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventGuest'], meta: { name: 'EventGuest' } }
  /**
   * Find zero or one EventGuest that matches the filter.
   * @param {EventGuestFindUniqueArgs} args - Arguments to find a EventGuest
   * @example
   * // Get one EventGuest
   * const eventGuest = await prisma.eventGuest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventGuestFindUniqueArgs>(args: Prisma.SelectSubset<T, EventGuestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventGuestClient<runtime.Types.Result.GetResult<Prisma.$EventGuestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventGuest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventGuestFindUniqueOrThrowArgs} args - Arguments to find a EventGuest
   * @example
   * // Get one EventGuest
   * const eventGuest = await prisma.eventGuest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventGuestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventGuestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventGuestClient<runtime.Types.Result.GetResult<Prisma.$EventGuestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventGuest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventGuestFindFirstArgs} args - Arguments to find a EventGuest
   * @example
   * // Get one EventGuest
   * const eventGuest = await prisma.eventGuest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventGuestFindFirstArgs>(args?: Prisma.SelectSubset<T, EventGuestFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventGuestClient<runtime.Types.Result.GetResult<Prisma.$EventGuestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventGuest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventGuestFindFirstOrThrowArgs} args - Arguments to find a EventGuest
   * @example
   * // Get one EventGuest
   * const eventGuest = await prisma.eventGuest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventGuestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventGuestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventGuestClient<runtime.Types.Result.GetResult<Prisma.$EventGuestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventGuests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventGuestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventGuests
   * const eventGuests = await prisma.eventGuest.findMany()
   * 
   * // Get first 10 EventGuests
   * const eventGuests = await prisma.eventGuest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventGuestWithIdOnly = await prisma.eventGuest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventGuestFindManyArgs>(args?: Prisma.SelectSubset<T, EventGuestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventGuestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventGuest.
   * @param {EventGuestCreateArgs} args - Arguments to create a EventGuest.
   * @example
   * // Create one EventGuest
   * const EventGuest = await prisma.eventGuest.create({
   *   data: {
   *     // ... data to create a EventGuest
   *   }
   * })
   * 
   */
  create<T extends EventGuestCreateArgs>(args: Prisma.SelectSubset<T, EventGuestCreateArgs<ExtArgs>>): Prisma.Prisma__EventGuestClient<runtime.Types.Result.GetResult<Prisma.$EventGuestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventGuests.
   * @param {EventGuestCreateManyArgs} args - Arguments to create many EventGuests.
   * @example
   * // Create many EventGuests
   * const eventGuest = await prisma.eventGuest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventGuestCreateManyArgs>(args?: Prisma.SelectSubset<T, EventGuestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventGuests and returns the data saved in the database.
   * @param {EventGuestCreateManyAndReturnArgs} args - Arguments to create many EventGuests.
   * @example
   * // Create many EventGuests
   * const eventGuest = await prisma.eventGuest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventGuests and only return the `id`
   * const eventGuestWithIdOnly = await prisma.eventGuest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventGuestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventGuestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventGuestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventGuest.
   * @param {EventGuestDeleteArgs} args - Arguments to delete one EventGuest.
   * @example
   * // Delete one EventGuest
   * const EventGuest = await prisma.eventGuest.delete({
   *   where: {
   *     // ... filter to delete one EventGuest
   *   }
   * })
   * 
   */
  delete<T extends EventGuestDeleteArgs>(args: Prisma.SelectSubset<T, EventGuestDeleteArgs<ExtArgs>>): Prisma.Prisma__EventGuestClient<runtime.Types.Result.GetResult<Prisma.$EventGuestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventGuest.
   * @param {EventGuestUpdateArgs} args - Arguments to update one EventGuest.
   * @example
   * // Update one EventGuest
   * const eventGuest = await prisma.eventGuest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventGuestUpdateArgs>(args: Prisma.SelectSubset<T, EventGuestUpdateArgs<ExtArgs>>): Prisma.Prisma__EventGuestClient<runtime.Types.Result.GetResult<Prisma.$EventGuestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventGuests.
   * @param {EventGuestDeleteManyArgs} args - Arguments to filter EventGuests to delete.
   * @example
   * // Delete a few EventGuests
   * const { count } = await prisma.eventGuest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventGuestDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventGuestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventGuests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventGuestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventGuests
   * const eventGuest = await prisma.eventGuest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventGuestUpdateManyArgs>(args: Prisma.SelectSubset<T, EventGuestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventGuests and returns the data updated in the database.
   * @param {EventGuestUpdateManyAndReturnArgs} args - Arguments to update many EventGuests.
   * @example
   * // Update many EventGuests
   * const eventGuest = await prisma.eventGuest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventGuests and only return the `id`
   * const eventGuestWithIdOnly = await prisma.eventGuest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventGuestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventGuestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventGuestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventGuest.
   * @param {EventGuestUpsertArgs} args - Arguments to update or create a EventGuest.
   * @example
   * // Update or create a EventGuest
   * const eventGuest = await prisma.eventGuest.upsert({
   *   create: {
   *     // ... data to create a EventGuest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventGuest we want to update
   *   }
   * })
   */
  upsert<T extends EventGuestUpsertArgs>(args: Prisma.SelectSubset<T, EventGuestUpsertArgs<ExtArgs>>): Prisma.Prisma__EventGuestClient<runtime.Types.Result.GetResult<Prisma.$EventGuestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventGuests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventGuestCountArgs} args - Arguments to filter EventGuests to count.
   * @example
   * // Count the number of EventGuests
   * const count = await prisma.eventGuest.count({
   *   where: {
   *     // ... the filter for the EventGuests we want to count
   *   }
   * })
  **/
  count<T extends EventGuestCountArgs>(
    args?: Prisma.Subset<T, EventGuestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventGuestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventGuest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventGuestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventGuestAggregateArgs>(args: Prisma.Subset<T, EventGuestAggregateArgs>): Prisma.PrismaPromise<GetEventGuestAggregateType<T>>

  /**
   * Group by EventGuest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventGuestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventGuestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventGuestGroupByArgs['orderBy'] }
      : { orderBy?: EventGuestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventGuestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventGuestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventGuest model
 */
readonly fields: EventGuestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventGuest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventGuestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  event<T extends Prisma.EventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDefaultArgs<ExtArgs>>): Prisma.Prisma__EventClient<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventGuest model
 */
export interface EventGuestFieldRefs {
  readonly id: Prisma.FieldRef<"EventGuest", 'String'>
  readonly eventId: Prisma.FieldRef<"EventGuest", 'String'>
  readonly name: Prisma.FieldRef<"EventGuest", 'String'>
  readonly documentEncrypted: Prisma.FieldRef<"EventGuest", 'String'>
  readonly createdAt: Prisma.FieldRef<"EventGuest", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"EventGuest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EventGuest findUnique
 */
export type EventGuestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventGuest
   */
  select?: Prisma.EventGuestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventGuest
   */
  omit?: Prisma.EventGuestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventGuestInclude<ExtArgs> | null
  /**
   * Filter, which EventGuest to fetch.
   */
  where: Prisma.EventGuestWhereUniqueInput
}

/**
 * EventGuest findUniqueOrThrow
 */
export type EventGuestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventGuest
   */
  select?: Prisma.EventGuestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventGuest
   */
  omit?: Prisma.EventGuestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventGuestInclude<ExtArgs> | null
  /**
   * Filter, which EventGuest to fetch.
   */
  where: Prisma.EventGuestWhereUniqueInput
}

/**
 * EventGuest findFirst
 */
export type EventGuestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventGuest
   */
  select?: Prisma.EventGuestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventGuest
   */
  omit?: Prisma.EventGuestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventGuestInclude<ExtArgs> | null
  /**
   * Filter, which EventGuest to fetch.
   */
  where?: Prisma.EventGuestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventGuests to fetch.
   */
  orderBy?: Prisma.EventGuestOrderByWithRelationInput | Prisma.EventGuestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventGuests.
   */
  cursor?: Prisma.EventGuestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventGuests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventGuests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventGuests.
   */
  distinct?: Prisma.EventGuestScalarFieldEnum | Prisma.EventGuestScalarFieldEnum[]
}

/**
 * EventGuest findFirstOrThrow
 */
export type EventGuestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventGuest
   */
  select?: Prisma.EventGuestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventGuest
   */
  omit?: Prisma.EventGuestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventGuestInclude<ExtArgs> | null
  /**
   * Filter, which EventGuest to fetch.
   */
  where?: Prisma.EventGuestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventGuests to fetch.
   */
  orderBy?: Prisma.EventGuestOrderByWithRelationInput | Prisma.EventGuestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventGuests.
   */
  cursor?: Prisma.EventGuestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventGuests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventGuests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventGuests.
   */
  distinct?: Prisma.EventGuestScalarFieldEnum | Prisma.EventGuestScalarFieldEnum[]
}

/**
 * EventGuest findMany
 */
export type EventGuestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventGuest
   */
  select?: Prisma.EventGuestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventGuest
   */
  omit?: Prisma.EventGuestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventGuestInclude<ExtArgs> | null
  /**
   * Filter, which EventGuests to fetch.
   */
  where?: Prisma.EventGuestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventGuests to fetch.
   */
  orderBy?: Prisma.EventGuestOrderByWithRelationInput | Prisma.EventGuestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventGuests.
   */
  cursor?: Prisma.EventGuestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventGuests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventGuests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventGuests.
   */
  distinct?: Prisma.EventGuestScalarFieldEnum | Prisma.EventGuestScalarFieldEnum[]
}

/**
 * EventGuest create
 */
export type EventGuestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventGuest
   */
  select?: Prisma.EventGuestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventGuest
   */
  omit?: Prisma.EventGuestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventGuestInclude<ExtArgs> | null
  /**
   * The data needed to create a EventGuest.
   */
  data: Prisma.XOR<Prisma.EventGuestCreateInput, Prisma.EventGuestUncheckedCreateInput>
}

/**
 * EventGuest createMany
 */
export type EventGuestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventGuests.
   */
  data: Prisma.EventGuestCreateManyInput | Prisma.EventGuestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EventGuest createManyAndReturn
 */
export type EventGuestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventGuest
   */
  select?: Prisma.EventGuestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventGuest
   */
  omit?: Prisma.EventGuestOmit<ExtArgs> | null
  /**
   * The data used to create many EventGuests.
   */
  data: Prisma.EventGuestCreateManyInput | Prisma.EventGuestCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventGuestIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EventGuest update
 */
export type EventGuestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventGuest
   */
  select?: Prisma.EventGuestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventGuest
   */
  omit?: Prisma.EventGuestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventGuestInclude<ExtArgs> | null
  /**
   * The data needed to update a EventGuest.
   */
  data: Prisma.XOR<Prisma.EventGuestUpdateInput, Prisma.EventGuestUncheckedUpdateInput>
  /**
   * Choose, which EventGuest to update.
   */
  where: Prisma.EventGuestWhereUniqueInput
}

/**
 * EventGuest updateMany
 */
export type EventGuestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventGuests.
   */
  data: Prisma.XOR<Prisma.EventGuestUpdateManyMutationInput, Prisma.EventGuestUncheckedUpdateManyInput>
  /**
   * Filter which EventGuests to update
   */
  where?: Prisma.EventGuestWhereInput
  /**
   * Limit how many EventGuests to update.
   */
  limit?: number
}

/**
 * EventGuest updateManyAndReturn
 */
export type EventGuestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventGuest
   */
  select?: Prisma.EventGuestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventGuest
   */
  omit?: Prisma.EventGuestOmit<ExtArgs> | null
  /**
   * The data used to update EventGuests.
   */
  data: Prisma.XOR<Prisma.EventGuestUpdateManyMutationInput, Prisma.EventGuestUncheckedUpdateManyInput>
  /**
   * Filter which EventGuests to update
   */
  where?: Prisma.EventGuestWhereInput
  /**
   * Limit how many EventGuests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventGuestIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EventGuest upsert
 */
export type EventGuestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventGuest
   */
  select?: Prisma.EventGuestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventGuest
   */
  omit?: Prisma.EventGuestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventGuestInclude<ExtArgs> | null
  /**
   * The filter to search for the EventGuest to update in case it exists.
   */
  where: Prisma.EventGuestWhereUniqueInput
  /**
   * In case the EventGuest found by the `where` argument doesn't exist, create a new EventGuest with this data.
   */
  create: Prisma.XOR<Prisma.EventGuestCreateInput, Prisma.EventGuestUncheckedCreateInput>
  /**
   * In case the EventGuest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventGuestUpdateInput, Prisma.EventGuestUncheckedUpdateInput>
}

/**
 * EventGuest delete
 */
export type EventGuestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventGuest
   */
  select?: Prisma.EventGuestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventGuest
   */
  omit?: Prisma.EventGuestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventGuestInclude<ExtArgs> | null
  /**
   * Filter which EventGuest to delete.
   */
  where: Prisma.EventGuestWhereUniqueInput
}

/**
 * EventGuest deleteMany
 */
export type EventGuestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventGuests to delete
   */
  where?: Prisma.EventGuestWhereInput
  /**
   * Limit how many EventGuests to delete.
   */
  limit?: number
}

/**
 * EventGuest without action
 */
export type EventGuestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventGuest
   */
  select?: Prisma.EventGuestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventGuest
   */
  omit?: Prisma.EventGuestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventGuestInclude<ExtArgs> | null
}
