
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  ADMIN: 'ADMIN',
  PORTARIA: 'PORTARIA'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const ResidentRelation = {
  PROPRIETARIO: 'PROPRIETARIO',
  INQUILINO: 'INQUILINO',
  DEPENDENTE: 'DEPENDENTE'
} as const

export type ResidentRelation = (typeof ResidentRelation)[keyof typeof ResidentRelation]


export const VehicleType = {
  CARRO: 'CARRO',
  MOTO: 'MOTO',
  OUTRO: 'OUTRO'
} as const

export type VehicleType = (typeof VehicleType)[keyof typeof VehicleType]
